[phases.setup]
nixPkgs = [
  'go',
]

[phases.build]
cmds = [
  "curl -L -O https://github.com/JTan2231/vizier-bot/releases/download/git/git",
  "export PATH=$PWD:$PATH",
]

[start]
cmd = "go run main.go"
