[phases.setup]
nixPkgs = [
  'gcc',
  'rustup',
  'go',
]
aptPkgs = ['unzip']

[phases.build]
cmds = [
  "rustup default stable",
  "curl -L -O https://github.com/JTan2231/vizier/archive/refs/tags/v0.0.2.zip",
  "unzip v0.0.2.zip && cd vizier-0.0.2 && (cargo build --release || cargo build --release) && mv target/release/vizier ..",
  "go build",
]

[start]
cmd = "./vizier-bot"
