[phases.setup]
nixPkgs = [
  'go',
  'gcc',
]
aptPkgs = ['unzip']

[phases.build]
cmds = [
  "curl -L -O https://github.com/git/git/archive/refs/tags/v2.51.0.zip",
  "unzip v2.51.0.zip && cd git-2.51.0 && make && cp git ..",
  "export PATH=$PWD:$PATH",
]

[start]
cmd = "go run main.go"
