[phases.setup]
nixPkgs = [
  'go',
]

[phases.build]
cmds = [
  "curl -L -O https://github.com/JTan2231/vizier-bot/releases/download/git/git",
  "go build"
]

[start]
cmd = "ls -l git && ./vizier-bot"
