[phases.setup]
nixPkgs = [
  'gcc',
  'rustup',
  'go',
  'pkg-config',
  'openssl',
]
aptPkgs = ['unzip']

[phases.build]
cmds = [
  "find / -name \"*nix*\" -prune -o -name \"*include*\" -type f -print",
  "rustup default stable",
  "curl -L -O https://github.com/JTan2231/vizier/archive/refs/tags/v0.0.2.zip",
  "unzip v0.0.2.zip && cd vizier-0.0.2 && (OPENSSL_DIR=/usr/lib/x86_64-linux-gnu cargo build --release || OPENSSL_DIR=/usr/lib/x86_64-linux-gnu cargo build --release) && mv target/release/vizier ..",
  "go build",
]

[start]
cmd = "./vizier-bot"
