[phases.setup]
nixPkgs = [
  'go',
]

[phases.build]
cmds = [
  "mkdir -p $HOME/bin",
  "curl -L -O https://github.com/git/git/archive/refs/tags/v2.51.0.zip",
  "unzip v2.51.0.zip && cd git-2.51.0 && make && cp git $HOME/bin/",
  "export PATH=$HOME/bin:$PATH",
]

[start]
cmd = "go run main.go"
