[phases.setup]
nixPkgs = [
  'gcc',
  'rustup',
  'go',
  'pkg-config',
  'openssl',
]
aptPkgs = ['unzip', 'libssl-dev']

[phases.build]
cmds = [
  "find / -name \"*nix*\" -prune -o -name \"*ssl*\" -type f -print",
  # "curl -L -O https://github.com/openssl/openssl/archive/refs/tags/openssl-3.6.0.zip",
  # "unzip openssl-3.6.0.zip && cd openssl-3.6.0.zip && ./Configure --prefix=/opt/openssl --openssldir=/usr/ssl && make && make install && cd ..",
  "rustup default stable",
  "curl -L -O https://github.com/JTan2231/vizier/archive/refs/tags/v0.0.2.zip",
  "unzip v0.0.2.zip && cd vizier-0.0.2 && (OPENSSL_DIR=/usr/include/openssl cargo build --release || OPENSSL_DIR=/usr/include/openssl cargo build --release) && mv target/release/vizier ..",
  "go build",
]

[start]
cmd = "./vizier-bot"
